- app/models/event.rb
- app/views/admin/competitors/_form.html.erb
- app/views/admin/dashboard/_events_with_limits.html.erb
- app/views/liquid/_registration_form.html.erb
- app/views/liquid/_schedule.html.erb
This fixes https://github.com/fw42/cubecomp/issues/104 and https://github.com/fw42/cubecomp/issues/105.
One issue was that I was showing the name (not the short name) and some events don't have a name (only a short name), which meant they appeared blank. Solution is to show the long name if it exists and otherwise the short name.
Other problem was that the form was showing events that weren't for registration (second rounds, breaks, etc.). Fix is to only show events that are explicitly for registration.
@Laura-O FYI
> Only show events that are for registration

- app/services/theme_file_renderer.rb
Fixes https://github.com/fw42/cubecomp/issues/115
Only show competitors on the public competitors table if they are registered for at least one event.
@SAuroux
> Dont show guests on public page

- app/assets/javascripts/admin.js
- app/assets/javascripts/competition_area.js
- app/assets/javascripts/wca-autocomplete.js.coffee
- vendor/assets/javascripts/jquery.ba-throttle-debounce.js
Uses http://benalman.com/code/projects/jquery-throttle-debounce/examples/debounce/
This debounces the WCA ID autocompletion and greatly reduces the number of external requests to the API. Typing my own WCA ID in one go will now only make one request. Previously it would make 5 (min length is 6, my ID is 10, so one request for characters 6,7,8,9,10).
Closes https://github.com/fw42/cubecomp/issues/103
@timhabermaas
> Debounce WCA typeahead

- app/models/competitor.rb
- app/validators/email_dns_validator.rb
- app/validators/email_validator.rb
- test/models/competitor_test.rb
Related to https://github.com/fw42/cubecomp/issues/5.
People would often mistype their email address, often with invalid domain names etc. (from my experience, at least one person per competition does it wrong).
This PR adds MX record validation to emails.
> Validate email domain MX record

- app/controllers/admin/competitions_controller.rb
- test/controllers/admin/competitions_controller_test.rb
Small bug introduced in https://github.com/fw42/cubecomp/pull/123.
Fixes https://github.com/fw42/cubecomp/issues/132.
> Don't redirect back to admin area after competition is updated

- app/controllers/admin/users_controller.rb
- app/services/user_policy.rb
- app/views/admin/users/_form.html.erb
- test/controllers/admin/users_controller_test.rb
Only allow to change the "Allowed to login" flag if the current user has higher permissions than the one that's being edited. In particular, don't allow users to change their own setting for "Allowed to login".
> Don't allow users to lock themselves out

- app/models/competitor.rb
- app/services/pricing_model/per_competition.rb
- test/controllers/admin/competitors_controller_test.rb
- test/models/competitor_test.rb
This fixes a bug where a competitor that is registered for only one event on a day would be considered to be "competing" (i.e. pay the competitor price, not the guest price), even if the event registration is on waiting list.
This PR fixes that and only considers competitors to be "competing" if they are participating in at least one event and are not on the waiting list for that event.
> fix bug in competing logic

- app/controllers/admin/theme_files_controller.rb
- test/controllers/admin/theme_files/competition_test.rb
Fixes a stupid bug that was found by @cubizh where only admins are allowed to import default themes. Everybody should be able to do that (for the competitions they have permission to login to). This PR fixes that.
> Allow everyone to import default themes

- app/controllers/admin/email_templates_controller.rb
- app/models/user.rb
- app/views/admin/email_templates/import_templates_form.html.erb
Similar bug as https://github.com/fw42/cubecomp/pull/155, also discovered by @cubizh.
Email templates are only supposed to be importable if you have permission to see the competition. That's on purpose. However, the form shows all competitions and then gives you a "forbidden" error when you actually try to import things.
This PR changes it so that the form only shows the competitions that you have access to login to.
> Fix email template form

- app/assets/stylesheets/competition_area.css.scss.erb
- app/services/theme_file_renderer.rb
- app/views/liquid/_venue_map.html.erb
- config/application.rb
Fixes https://github.com/fw42/cubecomp/issues/163.
@cubizh, FYI, this implements a `{{ venue_map }}` command that renders a map via the Google Maps Embed API. No GPS coordinates necessary, it will just look up the position from the venue address.
Size of the map is 500px by 500px by default, but can be overwritten via CSS (or I can change it if you think it's not a reasonable default).
@sauroux FYI
> {{ venue_map }}

- app/controllers/admin/events_controller.rb
- app/helpers/admin/competitors_helper.rb
- app/models/event.rb
- app/views/admin/competitors/_form.html.erb
- app/views/admin/dashboard/_events_with_limits.html.erb
- app/views/admin/events/_form.html.erb
- app/views/admin/events/_table.html.erb
- app/views/liquid/_registration_form.html.erb
- app/views/liquid/_schedule.html.erb
- db/migrate/20150517162903_drop_name_column.rb
- db/schema.rb
- db/seeds/example_competition.rb
- lib/wca_events.rb
- test/controllers/admin/events_controller_test.rb
- test/fixtures/events.yml
- test/models/event_test.rb
- test/services/email_template_renderer_test.rb
Closes https://github.com/fw42/cubecomp/issues/157.
This removes the "long name" attribute of events, from now on, they will only have a "name". This field was kinda useless in retrospect and sometimes the source of confusion.
Also, the "load" button for creating new events will now load the standard WCA event names.
For existing competitions, the long name will just be removed and the old short name will stay the same (so if you already created a competition with event names that are not the WCA standard event names, they will stay the way they are, not get automatically changed).
The only place on the competition website where you could even see the long name before was the registration form and the confirmation emails.
@cubizh @sauroux @Laura-O, all okay with this?
> Remove event long name

- app/views/liquid/_stats.html.erb
Fixes https://github.com/fw42/cubecomp/issues/211.
According to [this](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Date/UTC), the JavaScript `Date.UTC` function wants the month between 0 and 11, but the Ruby `Date#month` method returns it between 1 and 12.
> Fix month off-by-one in public stats

- app/models/event.rb
- app/services/csv_service.rb
- test/services/csv_service_test.rb
This addresses part of https://github.com/fw42/cubecomp/issues/219. If an event is not open for registration (either because it's open with waiting list or because it was open but now is closed), the CSV export would not include it. This PR fixes that and always includes all events that people were able to register for.
@SAuroux
> CSV export should include waiting list events

- app/services/csv_service.rb
- test/controllers/admin/competitors_controller_test.rb
- test/services/csv_service_test.rb
https://github.com/fw42/cubecomp/commit/90c93364 broke the CSV export. This PR fixes that.
Closes https://github.com/fw42/cubecomp/issues/219.
@SAuroux
> Fix CSV export

- app/models/event.rb
- app/services/theme_file_renderer.rb
- test/models/event_test.rb
This should fix https://github.com/fw42/cubecomp/issues/222.
We have short handles (2, 3, 4) and wca handles (222, 333, 444) for events. The shorter ones are for printing in the competitors table, just because they look nicer. The longer ones are used for the CSV export. You specify the short handle for your event and the code knows the long handle already (based on [this mapping](https://github.com/fw42/cubecomp/blob/c1fe0ea6ab0d60252361c7c1cd6d15fedf54f09c/lib/wca_events.rb)).
Previously, if someone would accidentally (or on purpose) use the original WCA handles as the handle for an event, a few things would break (https://github.com/fw42/cubecomp/issues/222 for example).
This PR (hopefully) fixes that by making the mapping a bit smarter (i.e. if no  WCA handle can be found based on the …
> Fix wca handle mapping

- db/seeds/themes/default/comparison.html
- db/seeds/themes/default/competitors.html
- db/seeds/themes/default/stats.html
In https://github.com/fw42/cubecomp/pull/182 and https://github.com/fw42/cubecomp/pull/149 I added those two features to all existing themes, but for some reason forgot to add it to the default theme. Fixing that here.
> Add stats and comparison to default theme

- app/controllers/front_page_controller.rb
- app/models/competition.rb
- db/migrate/20160408235324_default_force_custom_domain_ssl_to_false.rb
- db/schema.rb
- test/controllers/front_page_controller_test.rb
- test/models/competition_test.rb
Closes https://github.com/fw42/cubecomp/issues/215.
When loading cubecomp's front page via a domain that is the custom domain of at least one competition, this PR makes it so that the front page now only shows competitions that use that custom domain.
Loading cubecomp via the default domain will still show all competitions, even the ones that use custom domains.
> Custom domain frontpage should only show competitions for that domain

- app/models/competitor.rb
- app/views/admin/competitors/index.html.erb
- test/models/competitor_test.rb
This should fix #230.
This fix is not perfect as it ignores the possibility that a competition is taking place in two different years.
However, it is unlikely that a competition spans over two years, so in general it should be working as expected.
Feel free to ignore this PR if it doesn't meet your quality standards. :-)
> fix weekday of birthdays

- db/migrate/20170709195655_migrate_countries.rb
- db/schema.rb
Migrate countries to the current version of the list of [wca-states](https://github.com/thewca/wca-regulations/blob/draft/wca-states.md) (also see https://github.com/thewca/worldcubeassociation.org/pull/1650).
Checking our production database, there is exactly four countries that need to be migrated:
```
irb(main):041:0> countries = Country.pluck(:name);
irb(main):042:0* wca_countries = Wca::Country.pluck(:name);
irb(main):043:0* competitor_country_ids = Competitor.pluck('distinct(country_id)');
irb(main):044:0* competition_country_ids = Competition.pluck('distinct(country_id)');
irb(main):045:0* Country.where(name: countries - wca_countries).where(id: competitor_country_ids + competition_country_ids).map(&:name)
=> ["Aruba", "Korea", "Puerto Rico", "USA"]
```
Those countries are renamed …
> Migrate countries

- app/assets/javascripts/wca-autocomplete.js.coffee
Currently, the autocompletion for competitors who already have a WCA ID just splits the name into an array using whitespace as separator. It then assumes that the first element is the first name and the second element is the last name. So "John Doe Smith" becomes first name: "John", last name: "Doe" and "Smith" is ignored.
This PR fixes this by splitting the string at the first whitespace and making the remaining string the second element in the array. This is still not 100% correct if the competitor has two first names as the second first name and the last name are filled in as the last name. However, I think this is still better than just omitting the last name.
Background: there is a German competitor with two last names who repeatedly registered with only his first last name and I …
> Fix autocompletion for competitors with two first or last names
