app/controllers/admin/users_controller.rb, app/views/admin/users/_table.html.erb, app/views/admin/users/index.html.erb, test/controllers/admin/users_controller_test.rb
Closes https://github.com/fw42/cubecomp/issues/110
=> Divide users table by status

app/controllers/admin/competitions_controller.rb, app/models/competition.rb, app/views/admin/competitions/_form.html.erb, test/controllers/admin/competitions_controller_test.rb
Fixes https://github.com/fw42/cubecomp/issues/107.
@SAuroux FYI
=> Automatically create permission for owner when creating competition

app/controllers/admin/competitors_controller.rb, app/views/admin/competitors/index.html.erb, config/routes.rb, test/controllers/admin/competitors_controller_test.rb
Fixes https://github.com/fw42/cubecomp/issues/108
@SAuroux
=> Action button to mark competitor as paid

app/assets/javascripts/admin.js, app/helpers/admin/competitions_helper.rb, app/helpers/admin/users_helper.rb, app/views/admin/competitions/_form.html.erb, app/views/admin/users/_form.html.erb, vendor/assets/javascripts/jquery.nested_attributes.coffee
Fixes https://github.com/fw42/cubecomp/issues/119 (and a similar bug in the users edit form)
=> Fix nested attribute forms

app/assets/stylesheets/admin/nametags.css
Should fix https://github.com/fw42/cubecomp/issues/106
@Laura-O does this look good to you?
=> Fix nametags

app/controllers/admin/competitors_controller.rb, app/models/competitor.rb, app/views/admin/competitors/email_addresses.html.erb
Fixes https://github.com/fw42/cubecomp/issues/116
@SAuroux, this will show email addresses of competitors who are in the state "new", who haven't paid yet, and who are not marked as having free entrance.
=> Awaiting payment email addresses

app/controllers/admin/competitions_controller.rb, app/controllers/admin/competitors_controller.rb, app/controllers/admin/events_controller.rb, app/controllers/admin/theme_files_controller.rb, app/controllers/admin/users_controller.rb, test/controllers/admin/competitions_controller_test.rb, test/controllers/admin/competitors_controller_test.rb, test/controllers/admin/events_controller_test.rb, test/controllers/admin/theme_files/competition_test.rb, test/controllers/admin/theme_files/theme_test.rb, test/controllers/admin/users_controller_test.rb
UI flow wasn't consistent. Now every edit/new page redirects back to the index page after saving.
=> Consistently redirect back to index page after updating/creating

app/services/checklist_service.rb, test/services/checklist_service_test.rb
Fixes https://github.com/fw42/cubecomp/issues/128
=> Hide user comments on checklist

app/views/admin/competitors/_form.html.erb
shows when a competitor was created
requested by @SAuroux
=> Show "Registered on" for competitor

app/services/csv_service.rb
Closes https://github.com/fw42/cubecomp/issues/134
=> Rearrange CSV columns to match cubecomps.com

app/views/liquid/_registration_form.html.erb
Seems like this just causes confusion.
Closes https://github.com/fw42/cubecomp/issues/131.
=> Remove entrance fee from registration form

app/assets/javascripts/email_suggestions.js, app/assets/stylesheets/competition_area.css.scss.erb, app/views/liquid/_registration_form.html.erb
=> make id unique

app/controllers/admin/dashboard_controller.rb, app/services/competitor_statistics.rb, app/views/admin/dashboard/_competitor_statistics.html.erb, app/views/admin/dashboard/index.html.erb, test/controllers/admin/dashboard_controller_test.rb
Closes https://github.com/fw42/cubecomp/issues/96.
=> Competitor statistics

app/controllers/admin/users_controller.rb, app/models/user.rb, app/services/user_policy.rb, app/views/admin/users/_form.html.erb, test/controllers/admin/users_controller_test.rb, test/models/user_test.rb, test/services/user_policy_test.rb
Closes https://github.com/fw42/cubecomp/issues/74.
=> Require old password to set new password

app/assets/javascripts/admin/user.js, app/views/layouts/admin.html.erb, config/initializers/assets.rb, vendor/assets/javascripts/strength.js, vendor/assets/stylesheets/strength.css.scss
uses https://github.com/aarondo/Strength.js
=> Password strength indicator

db/migrate/20150419201441_add_stats_to_all_competitions.rb, db/schema.rb
Inject https://github.com/fw42/cubecomp/pull/148 into all themes
=> Ship highcharts to all competitions and themes

config/locales/pt.yml
The translation file is done (forgot to translate one line that's why I added another pull request, sorry)
=> Adding portuguese translation file

lib/wca_events.rb
Adding Skewb to the list of WCA official events
=> Adding skewb to list of WCA events

app/views/admin/events/_form.html.erb
Fixes https://github.com/fw42/cubecomp/issues/161.
=> Fix event state select

app/assets/stylesheets/admin.css.scss, app/controllers/admin/competitors_controller.rb, app/models/competitor.rb, app/views/admin/competitors/email_addresses.html.erb, app/views/admin/competitors/index.html.erb, config/routes.rb, db/migrate/20150516173814_change_disabled_to_cancelled.rb, db/schema.rb, test/controllers/admin/competitors_controller_test.rb
Fixes https://github.com/fw42/cubecomp/issues/158.
=> Rename competitor state "disabled" to "cancelled"

app/controllers/admin/events_controller.rb, app/models/event.rb, test/controllers/admin/events_controller_test.rb, test/fixtures/days.yml
Fixes https://github.com/fw42/cubecomp/issues/153.
=> Fix event import with duplicate

app/controllers/admin/competitions_controller.rb, app/controllers/competition_area_controller.rb, app/models/competition.rb, app/views/admin/competitions/_form.html.erb, config/application.rb, config/environments/production.rb, config/routes.rb, db/migrate/20150516210444_competitions_add_custom_domain.rb, db/schema.rb, test/controllers/competition_area_controller_test.rb
Closes https://github.com/fw42/cubecomp/issues/168.
=> Custom domains

app/liquid/filters/url.rb, config/application.rb, config/environments/production.rb
Follow-up to https://github.com/fw42/cubecomp/pull/171.
=> serve theme file images from asset host

app/controllers/front_page_controller.rb
Follow-up to https://github.com/fw42/cubecomp/pull/171.
=> Redirect frontpage to main domain

app/views/liquid/_stats.html.erb, config/locales/de.yml, config/locales/en.yml, config/locales/pt.yml
Fixes https://github.com/fw42/cubecomp/issues/170.
=> Translate newcomer and non-newcomer

app/controllers/admin/events_controller.rb, app/views/admin/events/_table.html.erb, config/routes.rb, test/controllers/admin/events_controller_test.rb
Fixes https://github.com/fw42/cubecomp/issues/172.
=> Destroy day

app/controllers/admin/competitors_controller.rb, app/controllers/admin/users_controller.rb, app/models/competitor.rb, app/models/concerns/has_wca_id.rb, app/models/user.rb, app/models/wca/person.rb, app/models/wca/ranks_average.rb, app/models/wca/ranks_single.rb, app/models/wca/result.rb, app/services/wca_nametag_service.rb, app/services/wca_time.rb, app/views/admin/competitors/nametags.html.erb, app/views/admin/users/_form.html.erb, db/migrate/20150518004639_users_add_wca_id.rb, db/migrate/20150518005011_backfill_user_delegate.rb, db/migrate/20150518010026_remove_delegate_from_nametag.rb, db/schema.rb, test/controllers/admin/users_controller_test.rb
Closes https://github.com/fw42/cubecomp/issues/52.
=> Wca nametags

app/assets/stylesheets/competition_area.css.scss.erb, app/models/event.rb, app/models/wca/ranks_average.rb, app/models/wca/ranks_single.rb, app/services/theme_file_renderer.rb, app/services/wca_nametag_service.rb, app/services/wca_time.rb, app/views/liquid/_comparison.html.erb, config/locales/de.yml, config/locales/en.yml, config/locales/pt.yml, db/migrate/20150518180507_backfill_psych_sheets.rb, db/schema.rb
Closes https://github.com/fw42/cubecomp/issues/53.
=> Competitor comparison

app/views/liquid/_competitors.html.erb
Closes https://github.com/fw42/cubecomp/issues/191.
=> Remove city name from public competitor page

app/services/wca_nametag_service.rb
Fixes https://github.com/fw42/cubecomp/issues/188
=> Fix nametag off-by-one

app/views/liquid/_competitors.html.erb, app/views/liquid/_registration_form.html.erb, config/locales/de.yml, config/locales/en.yml, config/locales/pt.yml
Closes https://github.com/fw42/cubecomp/issues/186.
=> "Citizen of" instead of "Country"

app/helpers/admin_helper.rb
Fixes https://github.com/fw42/cubecomp/issues/196.
@sauroux
=> Fix time spacing

app/views/admin/competitors/nametags.html.erb
https://github.com/fw42/cubecomp/issues/191#issuecomment-136179046
=> Remove local city from nametags

app/services/checklist_service.rb, test/services/checklist_service_test.rb
Fixes https://github.com/fw42/cubecomp/issues/204
=> Hide newcomer note on checklist for guests

app/controllers/admin/events_controller.rb, app/models/competitor.rb, app/views/admin/events/_table.html.erb
Fixes https://github.com/fw42/cubecomp/issues/199.
=> Only count confirmed registrations

bin/wca_db_update.sh
=> Fix sed syntax for Mac OS X

app/models/locale.rb, config/locales/it.yml
=> Add italian locale

app/services/csv_service.rb
This should address https://github.com/fw42/cubecomp/pull/135#issuecomment-198005291.
@SAuroux @cubizh
=> Fix cubecomps.com CSV export

app/controllers/admin/competitors_controller.rb, app/views/admin/competitors/csv.html.erb, config/routes.rb, test/controllers/admin/competitors_controller_test.rb
=> Competitors CSV export download link

app/services/theme_file_renderer.rb, app/views/liquid/_comparison.html.erb
Adds a dropdown box so that you can chose what to sort by. I think this is a somewhat reasonable way to address https://github.com/fw42/cubecomp/issues/184.
=> Allow to customize sort order in comparison view

app/services/competitor_statistics.rb, app/views/admin/dashboard/_competitor_statistics.html.erb
Closes https://github.com/fw42/cubecomp/issues/195.
Sorry this took so long... @Laura-O
=> Exclude guests from competitor statistics

app/assets/javascripts/wca-autocomplete.js.coffee, app/controllers/admin/competitors_controller.rb, app/controllers/competition_area/competitors_controller.rb, app/models/competitor.rb, app/services/csv_service.rb, app/views/admin/competitor_email/new.html.erb, app/views/admin/competitors/_form.html.erb, app/views/admin/competitors/index.html.erb, app/views/liquid/_registration_form.html.erb, config/locales/de.yml, config/locales/en.yml, config/locales/fr.yml, config/locales/it.yml, config/locales/pt.yml, db/migrate/20180304131900_competitors_add_gender_column.rb, db/migrate/20180304132024_competitors_migrate_gender_column.rb, db/migrate/20180304135200_competitors_drop_male_column.rb, db/schema.rb, db/seeds/example_competition.rb, test/controllers/admin/competitors_controller_test.rb, test/controllers/competition_area/competitors_controller_test.rb, test/fixtures/competitors.yml, test/models/competitor_test.rb
Closes https://github.com/fw42/cubecomp/issues/246.
=> Add support for 'other' gender

app/lib/wca_events.rb
Updated list of event names to match the new naming convention.
=> Fix WCA event names
